### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [offbit/char-models#1]
Nice work. I tried running your code (both rnns and cnns files) but I get this error : 
`"TypeError: Expected binary or unicode string, got input_2"`
on line 121 of doc-rnn2.py `"embedded = Lambda(binarize, output_shape=binarize_outshape)(in_sentence)"`
Do you have any suggestions for what to do to fix it?

Thank you.
Cristina

**Comment by offbit** [comment]
Hi, 
Are you using an up to date **_tensorflow_** as backend? anything > **0.8** should be fine.
I haven't seen the issue before. I'm guessing its either **_keras_** or **_tensorflow_** versioning problem.

**Comment by ghost** [comment]
Hi, 
Thank you for your reply. I am using **tensorflow** 0.8. 
Which version of **keras** are you using?

**Comment by offbit** [comment]
Right now I just tested it on a 1.0.0 and works just fine. 
I've been running it in both OSX and Ubuntu

**Comment by ghost** [comment]
Hi, 
Fixed it. I was using **keras** with **theano** as _backend_. I changed the keras json file to use **tensorflow** as _backend_. Thank you again for your prompt reply.
